import lib/type.p
import lib/void.p
import lib/eq.p
import lib/unit.p
import lib/sigma.p
import lib/algebra.p
import lib/combinators.p
import lib/functor.p
import lib/monad.p
import lib/monoid.p
import lib/singleton.p
import lib/bool.p
import lib/sum.p
import lib/Maybe.p
